- name: Proxmox vm creation playbook.
  hosts: proxmox
  tasks:

    - include_vars: vars.yml

    - name: Create a new vm from a template.
      proxmox_kvm:
        api_user    : "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host    : "{{ proxmox_ip }}"
        clone       : "{{ vm_template }}"
        name        : "{{ vm_name }}"
        node        : "{{ proxmox_node }}"
        storage     : "{{ storage }}"
        format      : "{{ format }}"
        timeout     : "{{ vm_timeout }}"

    - debug: 
        msg: "Your vm {{ vm_name }} is ready (stopped) on node {{ proxmox_node }}!"